### ISSUE TITLE
sync_batchnorm文件缺失

### ISSUE THREAD

**Issue by shangchengPKU** [ken-ouyang/PGMPI#1]
尊敬的作者你好，您出色的工作令我十分惊叹，但是我在自己运行代码的时候出现了错误，所以是否是漏传了某个文件？

(pgmpi) shangcheng@lanever-Super-Server:~/PGMPI$ sh train.sh
Traceback (most recent call last):
  File "train.py", line 30, in <module>
    from models.networks.generator import SPADEGenerator
  File "/home/shangcheng/PGMPI/models/networks/__init__.py", line 8, in <module>
    from models.networks.loss import *
  File "/home/shangcheng/PGMPI/models/networks/loss.py", line 9, in <module>
    from models.networks.architecture import VGG19
  File "/home/shangcheng/PGMPI/models/networks/architecture.py", line 11, in <module>
    from models.networks.normalization import SPADE
  File "/home/shangcheng/PGMPI/models/networks/normalization.py", line 10, in <module>
    from models.networks.sync_batchnorm import SynchronizedBatchNorm2d
ModuleNotFoundError: No module named 'models.networks.sync_batchnorm'

**Comment by ken-ouyang** [comment]
Hi~ 谢谢你对我们工作的关注 这个文件在SPADE的repo下可以有安装方法 https://github.com/NVlabs/SPADE 但是现在release的版本是基于unet测试的 要用SPADE可能还需要些额外的修改 推荐网络结构设置为unet

**Comment by shangchengPKU** [comment]
您好，感谢您的回复，但是我在运行代码的时候，并没有进行任何代码上的修改，可是还是有上述的错误，您的意思是说，我是不是需要修改代码的那些具体地方呢？如果是的话，可以麻烦具体告知一下吗？感谢！！！

**Comment by shangchengPKU** [comment]
感谢！问题已解决！
